### ISSUE TITLE
Treelist Allows Duplicates

### ISSUE THREAD

**Issue by erzr** [Velir/SitecoreFieldSuite#5]
The Treelist field is allowing the same item to be selected multiple times (see attached photo.)
![1-15-2013 2-58-24 PM](https://f.cloud.github.com/assets/1308218/69086/2b61e588-5f4e-11e2-9d1c-74ff2a416dbb.png)

**Comment by tbraga** [comment]
Is the source set to not select duplicates?

**Comment by erzr** [comment]
Setting "AllowMultipleSelection" to no fixed this, Thanks Tim!
